__METADATA__
{
  "v3Meta": {
    "objectGuid": "e6fde5f5-2b5b-44e3-98cd-11150a26bf8a",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM Main

VAR
END_VAR
__IMPLEMENTATION__
Main_IO();

Main_Instruments();

Main_Equipment();

Main_Process();
