__METADATA__
{
  "v3Meta": {
    "objectGuid": "7698794f-a425-4131-bf5f-3868cf5ca815",
    "objectTypeGuid": "8ac092e5-3128-4e26-9e7e-11016c6684f2",
    "embeddedObjectTypeGuids": [
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__IMPLEMENTATION__
// Not Ready Alarms
// No Not Ready Alarms defined


// Failure Alarms
equip.Failure[0].Value := equip.PLC.BOOL0[1];	//VFD Fault


// Interlock Alarms
// No Interlock Alarms defined


// Warning Alarms
// No Warning Alarms defined
